allow specifying regname for GinBrowse ++yank
lambdalisue/gin.vim pull request #112
Opened 2023-11-10 14:44 UTC by atusy

SSIA

- 👍 add optional reg argument to yank()
- 👍 allow specifying register to GinBrowser ++yank
- 🌿 test yank() with a explicit register
- 📝 document GinBrowse ++yank={regname}

2023-11-10 15:21 UTC, lambdalisue requested changes

2023-11-10 15:21 UTC, lambdalisue commented on denops/gin/command/browse/command.ts
> +  yank: string | boolean;
Please don't make it required.

2023-11-10 15:22 UTC, atusy commented on denops/gin/command/browse/command.ts
> +  yank: string | boolean;
got it

2023-11-10 15:24 UTC, atusy commented on denops/gin/command/browse/command.ts
> +  yank: string | boolean;
oops I made wrong commit

2023-11-10 15:26 UTC, atusy commented on denops/gin/command/browse/command.ts
> +  yank: string | boolean;
should be fine now

2023-11-11 11:38 UTC, lambdalisue approved these changes
LGTM　Thanks 🎉

2023-11-11 11:38 UTC, merged